### ISSUE TITLE
Create Input component

### ISSUE THREAD

**Issue by neronim1141** [neronim1141/rental-board#3]
Create Input component with the use of clsx
expand the default input props with:

- [x] size (sm,md)

input shuld have border which will tell user things about its state:

- [x]  default it should be greylike color
- [x]  if hasError prop is defined and passed it should change to warning
- [x]  on [focus](https://tailwindcss.com/docs/hover-focus-and-other-states) it should change to primary or warning color
- [x] should change background color on hover

**Comment by neronim1141** [comment]
pull request gdzie?

**Comment by KKocot** [comment]
nie wiem xd
